export const DECK = [
  { value: 'A', suit: 'club' },
  { value: 'A', suit: 'diamond' },
  { value: 'A', suit: 'heart' },
  { value: 'A', suit: 'spade' },
  { value: '2', suit: 'club' },
  { value: '2', suit: 'diamond' },
  { value: '2', suit: 'heart' },
  { value: '2', suit: 'spade' },
  { value: '3', suit: 'club' },
  { value: '3', suit: 'diamond' },
  { value: '3', suit: 'heart' },
  { value: '3', suit: 'spade' },
  { value: '4', suit: 'club' },
  { value: '4', suit: 'diamond' },
  { value: '4', suit: 'heart' },
  { value: '4', suit: 'spade' },
  { value: '5', suit: 'club' },
  { value: '5', suit: 'diamond' },
  { value: '5', suit: 'heart' },
  { value: '5', suit: 'spade' },
  { value: '6', suit: 'club' },
  { value: '6', suit: 'diamond' },
  { value: '6', suit: 'heart' },
  { value: '6', suit: 'spade' },
  { value: '7', suit: 'club' },
  { value: '7', suit: 'diamond' },
  { value: '7', suit: 'heart' },
  { value: '7', suit: 'spade' },
  { value: '8', suit: 'club' },
  { value: '8', suit: 'diamond' },
  { value: '8', suit: 'heart' },
  { value: '8', suit: 'spade' },
  { value: '9', suit: 'club' },
  { value: '9', suit: 'diamond' },
  { value: '9', suit: 'heart' },
  { value: '9', suit: 'spade' },
  { value: '10', suit: 'club' },
  { value: '10', suit: 'diamond' },
  { value: '10', suit: 'heart' },
  { value: '10', suit: 'spade' },
  { value: 'J', suit: 'club' },
  { value: 'J', suit: 'diamond' },
  { value: 'J', suit: 'heart' },
  { value: 'J', suit: 'spade' },
  { value: 'Q', suit: 'club' },
  { value: 'Q', suit: 'diamond' },
  { value: 'Q', suit: 'heart' },
  { value: 'Q', suit: 'spade' },
  { value: 'K', suit: 'club' },
  { value: 'K', suit: 'diamond' },
  { value: 'K', suit: 'heart' },
  { value: 'K', suit: 'spade' },
];

export const NUMBER_OF_CARDS_PER_PLAYER = 9;
export const PLAYERS_NUMBER = 2;
export const NUMBER_OF_CARDS_TO_DISTRIBUTE = NUMBER_OF_CARDS_PER_PLAYER * PLAYERS_NUMBER;
export const SET_SIZE = 3;
